{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperuplink.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperuplink.labels" . | nindent 4 }}
  {{- with (merge (deepCopy .Values.serviceAccount.annotations) .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
