[General]
Mode = "development"

[Logging]
Level = "debug"

[Redis]
Addresses = ["127.0.0.1:6379"]

[Database]
Connection = "postgres://postgres:postgres@localhost:5432/hyperuplink_dev?sslmode=disable"

[Server]
Enable             = true
BindIP             = "0.0.0.0"
Port               = 3000
BodyLimit          = 67108864
Concurrency        = 262144
ProxyHeader        = "" # "X-Forwarded-For"
EnableIPValidation = false
TrustProxy         = false
TrustLoopback      = true
TrustProxies       = []
ReduceMemoryUsage  = false
ServerHeader       = ""

[API]
Enable             = true
BindIP             = "0.0.0.0"
Port               = 3001
BodyLimit          = 67108864
Concurrency        = 262144
ProxyHeader        = "" # "X-Forwarded-For"
EnableIPValidation = false
TrustProxy         = false
TrustLoopback      = true
TrustProxies       = []
ReduceMemoryUsage  = false
ServerHeader       = ""

[Users]
PromoteAdmin = ["dummy1@example.com", "dummy2@example.com"]

# [[AuthProvider]]
# Type = "github"
# Key = "XxXXxXXXXxXxXXXXXXXX"
# Secret = "XXxXxXXXxXXXXXXxxXXxXxXXxXXXXXXXxxXxXXXx"
# Scopes = ["read:user", "user:email"]

# [[Target]]
# ID = "notifications"
# Type = "email"
# Email.SMTPServer = "smtp.example.org"
# Email.SMTPTLSPolicy = 0
# Email.SMTPAuthType = "AUTODISCOVER"
# Email.SMTPUsername = "user"
# Email.SMTPPassword = "pass"
# Email.From.Email = "reply@example.org"
# Email.From.Name = "Example.org"

# [[Target]]
# ID = "jabber"
# Type = "xmpp"
# XMPP.Server ="jabber.example.org:5222"
# XMPP.InsecureSkipVerify = false
# XMPP.Username = "hello@example.org"
# XMPP.Password = "swordfish123"

[[Target]]
ID = "debug-email"
Type = "debug"
Debug.Emulates = "email"
Debug.Path = "/tmp/hyperuplink-messages"

[[Target]]
ID = "debug-xmpp"
Type = "debug"
Debug.Emulates = "xmpp"
Debug.Path = "/tmp/hyperuplink-messages"

[[Storage]]
ID = "remote-storage"
Type = "S3"
S3.Endpoint = "http://localhost:9000"
S3.Region = "us-east-1"
S3.AccessKey = "minioadmin"
S3.SecretKey = "minioadmin"
S3.PublicURL = "http://localhost:9000"
S3.PublicDownload = true
S3.PresignedDownload = false

[[Storage]]
ID = "local-storage"
Type = "Local"
Local.Path = "/tmp/www"
Local.PublicURI = "/media"
